FROM centos:7.4.1708

RUN yum install -y \
	openssl \
	openssl-devel \
	gcc \
	make \
	bzip2 \
	unzip \
	libtalloc-devel \
	libaio
RUN mkdir /mtmp \
	&& chmod 777 -R /mtmp \
	&& mkdir /opt/oracle \
	&& chmod 777 -R /opt/oracle

COPY resources /mtmp

RUN cd /mtmp \
	&& tar -xvf freeradius-server-3.0.17.tar.bz2 \
	&& unzip -d /opt/oracle/ instantclient-basic-linux.x64-11.2.0.4.0.zip \
	&& unzip -d /opt/oracle/ instantclient-sdk-linux.x64-11.2.0.4.0.zip	\
	&&	cd /opt/oracle/instantclient_11_2 \
	&&	ln -s libclntsh.so.11.1 libclntsh.so \
	&&	ln -s libocci.so.11.1 libocci.so \
	&& cp libnnz11.so /usr/local/lib \
	&& cp libclntsh.so /usr/local/lib \
	&& cp libclntsh.so.11.1 /usr/local/lib \
	&& cp libocci.so /usr/local/lib \
	&& cp libociei.so /usr/local/lib \	
	&& ldconfig \
	&& cd /mtmp/freeradius-server-3.0.17 && ./configure \
		--with-oracle-include-dir=/opt/oracle/instantclient_11_2/sdk/include/ \
		--with-oracle-lib-dir=/opt/oracle/instantclient_11_2/ \
	&& make \
	&& make install

COPY configs/test /mtmp

RUN cd /mtmp \
&& cp radiusd.conf /usr/local/etc/raddb/radiusd.conf \
&& cp clients.conf /usr/local/etc/raddb/clients.conf \
&& cp sql /usr/local/etc/raddb/mods-available/sql \
#&& cp coa /usr/local/etc/raddb/sites-available/coa \
&& cp dictionary /usr/local/etc/raddb/dictionary \
#&& cp originate-coa /usr/local/etc/raddb/sites-available/originate-coa \
#&& cp ippool /usr/local/etc/raddb/mods-available/ippool \
&& cp linelog /usr/local/etc/raddb/mods-available/linelog \
&& cp default /usr/local/etc/raddb/sites-enabled/default

RUN cd /usr/local/etc/raddb/mods-enabled \
&& ln -s ../mods-available/sql sql \
#&& ln -s ../mods-available/ippool ippool \
&& rm -rf /usr/local/etc/raddb/sites-enabled/inner-tunnel

#RUN cd /usr/local/etc/raddb/sites-enabled \
#&& ln -s ../sites-available/originate-coa originate-coa \
#&& ln -s ../sites-available/coa coa

RUN rm -rf /mtmp
RUN radiusd -X

RUN head -1 /usr/local/etc/raddb/radiusd.conf \
&& head -1 /usr/local/etc/raddb/clients.conf \
&& head -1 /usr/local/etc/raddb/mods-available/sql \
&& head -1 /usr/local/etc/raddb/mods-available/linelog \
&& head -1 /usr/local/etc/raddb/sites-enabled/default \
#&& head -1 /usr/local/etc/raddb/sites-enabled/coa
EXPOSE \
    1812/udp \
    1813/udp

