version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    environment:
      cluster.name: 'docker-cluster'
      bootstrap.memory_lock: 'false'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - /nfsshares/elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      replicas: 2
    networks:
      - ellk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    volumes:
      - /nfsshares/logstash_data/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /nfsshares/resources/oracle/client/ojdbc7.jar:/bin/ojdbc7.jar
    depends_on:
      - elasticsearch
    deploy:
      replicas: 2
    networks:
      - ellk

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 30s
    networks:
      - ellk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    ports:
      - '88:5601'
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 2
    networks:
      - ellk
networks:
  ellk:
