apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  externalIPs:
  - 10.90.2.41
  - 10.90.2.51
  - 10.90.2.61
  - 10.90.2.42
  - 10.90.2.52
  - 10.90.2.62
  - 10.90.2.111
  selector:
    app: ingress-nginx
