#This prospector captures the docker logs
- input_type: log
  protocol.udp:
    host: "localhost:9000"
  paths:
    - /hostfs/var/lib/docker/containers/*/*.log
#    - /var/log/host/messages*
#    - /var/log/host/maillog*
#  json.keys_under_root: true
#  json.overwrite_keys: true
  close_inactive: 24h
  close_renamed: true
 # pipeline: docker-logs