--DROP USER MIGRATION_SOURCE CASCADE;

CREATE USER MIGRATION_SOURCE
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE IBATBS
  TEMPORARY TABLESPACE IBATMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for MIGRATION_SOURCE 
  GRANT CONNECT TO MIGRATION_SOURCE;
  ALTER USER MIGRATION_SOURCE DEFAULT ROLE ALL;
  -- 12 System Privileges for MIGRATION_SOURCE 
  GRANT ALTER SESSION TO MIGRATION_SOURCE;
  GRANT CREATE ANY SYNONYM TO MIGRATION_SOURCE;
  GRANT CREATE JOB TO MIGRATION_SOURCE;
  GRANT CREATE MATERIALIZED VIEW TO MIGRATION_SOURCE;
  GRANT CREATE PROCEDURE TO MIGRATION_SOURCE;
  GRANT CREATE PUBLIC SYNONYM TO MIGRATION_SOURCE;
  GRANT CREATE SEQUENCE TO MIGRATION_SOURCE;
  GRANT CREATE SESSION TO MIGRATION_SOURCE;
  GRANT CREATE TABLE TO MIGRATION_SOURCE;
  GRANT CREATE TRIGGER TO MIGRATION_SOURCE;
  GRANT CREATE TYPE TO MIGRATION_SOURCE;
  GRANT CREATE VIEW TO MIGRATION_SOURCE;
  -- 2 Tablespace Quotas for MIGRATION_SOURCE 
  ALTER USER MIGRATION_SOURCE QUOTA UNLIMITED ON IBATBS;
  ALTER USER MIGRATION_SOURCE QUOTA UNLIMITED ON MIGRATIONTBS;
  -- 12 Object Privileges for MIGRATION_SOURCE 
    GRANT SELECT ON IBAMVP.ACTIV_SUB_TYPES TO MIGRATION_SOURCE;
    GRANT SELECT ON IBAMVP.DIS_TSC_ARRAY_BURDEN TO MIGRATION_SOURCE;
    GRANT SELECT ON IBAMVP.DIS_TSC_ARRAY_DISCOUNT TO MIGRATION_SOURCE;
    GRANT SELECT ON IBAMVP.DIS_TSC_VERSION TO MIGRATION_SOURCE;
    GRANT EXECUTE ON IBAMVP.PKG_UTILS TO MIGRATION_SOURCE;
    GRANT SELECT ON IBAMVP.VAT_RATES TO MIGRATION_SOURCE;
    GRANT SELECT ON MIGRATION_TARGET.ACTIV_SUB_TYPES TO MIGRATION_SOURCE;
    GRANT SELECT ON MIGRATION_TARGET.DIS_TSC_ARRAY_BURDEN TO MIGRATION_SOURCE;
    GRANT SELECT ON MIGRATION_TARGET.DIS_TSC_ARRAY_DISCOUNT TO MIGRATION_SOURCE;
    GRANT SELECT ON MIGRATION_TARGET.DIS_TSC_VERSION TO MIGRATION_SOURCE;
    GRANT EXECUTE ON MIGRATION_TARGET.PKG_UTILS TO MIGRATION_SOURCE;
    GRANT SELECT ON MIGRATION_TARGET.VAT_RATES TO MIGRATION_SOURCE;


---DROP USER MIGRATION_TARGET CASCADE;

CREATE USER MIGRATION_TARGET
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE IBATBS
  TEMPORARY TABLESPACE IBATMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for MIGRATION_TARGET 
  GRANT CONNECT TO MIGRATION_TARGET;
  ALTER USER MIGRATION_TARGET DEFAULT ROLE ALL;
  -- 21 System Privileges for MIGRATION_TARGET 
  GRANT ALTER SESSION TO MIGRATION_TARGET;
  GRANT CREATE ANY SYNONYM TO MIGRATION_TARGET;
  GRANT CREATE ANY TABLE TO MIGRATION_TARGET;
  GRANT CREATE ANY TYPE TO MIGRATION_TARGET;
  GRANT CREATE ANY VIEW TO MIGRATION_TARGET;
  GRANT CREATE JOB TO MIGRATION_TARGET;
  GRANT CREATE MATERIALIZED VIEW TO MIGRATION_TARGET;
  GRANT CREATE PROCEDURE TO MIGRATION_TARGET;
  GRANT CREATE PUBLIC SYNONYM TO MIGRATION_TARGET;
  GRANT CREATE SEQUENCE TO MIGRATION_TARGET;
  GRANT CREATE SESSION TO MIGRATION_TARGET;
  GRANT CREATE TABLE TO MIGRATION_TARGET;
  GRANT CREATE TABLESPACE TO MIGRATION_TARGET;
  GRANT CREATE TRIGGER TO MIGRATION_TARGET;
  GRANT CREATE TYPE TO MIGRATION_TARGET;
  GRANT CREATE VIEW TO MIGRATION_TARGET;
  GRANT DEBUG ANY PROCEDURE TO MIGRATION_TARGET;
  GRANT DEBUG CONNECT SESSION TO MIGRATION_TARGET;
  GRANT EXECUTE ANY PROCEDURE TO MIGRATION_TARGET;
  GRANT EXECUTE ANY PROGRAM TO MIGRATION_TARGET;
  GRANT UPDATE ANY TABLE TO MIGRATION_TARGET;
  -- 2 Tablespace Quotas for MIGRATION_TARGET 
  ALTER USER MIGRATION_TARGET QUOTA UNLIMITED ON IBATBS;
  ALTER USER MIGRATION_TARGET QUOTA UNLIMITED ON MIGRATIONTBS;
  -- 6 Object Privileges for MIGRATION_TARGET 
    GRANT SELECT ON IBAMVP.ACTIV_SUB_TYPES TO MIGRATION_TARGET;
    GRANT SELECT ON IBAMVP.DICT_MV TO MIGRATION_TARGET;
    GRANT SELECT ON IBAMVP.DICT_SIMPLE TO MIGRATION_TARGET;
    GRANT SELECT ON IBAMVP.DICT_VW TO MIGRATION_TARGET;
    GRANT EXECUTE ON IBAMVP.PKG_UTILS TO MIGRATION_TARGET;
    GRANT SELECT ON IBAMVP.VAT_RATES TO MIGRATION_TARGET;


---DROP USER MSACCESS CASCADE;

CREATE USER MSACCESS
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE IBATBS
  TEMPORARY TABLESPACE IBATMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for MSACCESS 
  GRANT RESOURCE TO MSACCESS;
  ALTER USER MSACCESS DEFAULT ROLE ALL;
  -- 178 System Privileges for MSACCESS 
  GRANT ADMINISTER ANY SQL TUNING SET TO MSACCESS;
  GRANT ADMINISTER DATABASE TRIGGER TO MSACCESS;
  GRANT ADMINISTER SQL MANAGEMENT OBJECT TO MSACCESS;
  GRANT ADMINISTER SQL TUNING SET TO MSACCESS;
  GRANT ADVISOR TO MSACCESS;
  GRANT ALTER ANY ASSEMBLY TO MSACCESS;
  GRANT ALTER ANY CLUSTER TO MSACCESS;
  GRANT ALTER ANY CUBE TO MSACCESS;
  GRANT ALTER ANY CUBE DIMENSION TO MSACCESS;
  GRANT ALTER ANY DIMENSION TO MSACCESS;
  GRANT ALTER ANY EDITION TO MSACCESS;
  GRANT ALTER ANY INDEX TO MSACCESS;
  GRANT ALTER ANY INDEXTYPE TO MSACCESS;
  GRANT ALTER ANY LIBRARY TO MSACCESS;
  GRANT ALTER ANY MATERIALIZED VIEW TO MSACCESS;
  GRANT ALTER ANY MINING MODEL TO MSACCESS;
  GRANT ALTER ANY OPERATOR TO MSACCESS;
  GRANT ALTER ANY OUTLINE TO MSACCESS;
  GRANT ALTER ANY PROCEDURE TO MSACCESS;
  GRANT ALTER ANY ROLE TO MSACCESS;
  GRANT ALTER ANY SEQUENCE TO MSACCESS;
  GRANT ALTER ANY SQL PROFILE TO MSACCESS;
  GRANT ALTER ANY TABLE TO MSACCESS;
  GRANT ALTER ANY TRIGGER TO MSACCESS;
  GRANT ALTER ANY TYPE TO MSACCESS;
  GRANT ALTER DATABASE TO MSACCESS;
  GRANT ALTER PROFILE TO MSACCESS;
  GRANT ALTER RESOURCE COST TO MSACCESS;
  GRANT ALTER ROLLBACK SEGMENT TO MSACCESS;
  GRANT ALTER SESSION TO MSACCESS;
  GRANT ALTER SYSTEM TO MSACCESS;
  GRANT ALTER TABLESPACE TO MSACCESS;
  GRANT ALTER USER TO MSACCESS;
  GRANT ANALYZE ANY TO MSACCESS;
  GRANT AUDIT ANY TO MSACCESS;
  GRANT AUDIT SYSTEM TO MSACCESS;
  GRANT BACKUP ANY TABLE TO MSACCESS;
  GRANT BECOME USER TO MSACCESS;
  GRANT CHANGE NOTIFICATION TO MSACCESS;
  GRANT COMMENT ANY MINING MODEL TO MSACCESS;
  GRANT COMMENT ANY TABLE TO MSACCESS;
  GRANT CREATE ANY ASSEMBLY TO MSACCESS;
  GRANT CREATE ANY CLUSTER TO MSACCESS;
  GRANT CREATE ANY CONTEXT TO MSACCESS;
  GRANT CREATE ANY CUBE TO MSACCESS;
  GRANT CREATE ANY CUBE BUILD PROCESS TO MSACCESS;
  GRANT CREATE ANY CUBE DIMENSION TO MSACCESS;
  GRANT CREATE ANY DIMENSION TO MSACCESS;
  GRANT CREATE ANY DIRECTORY TO MSACCESS;
  GRANT CREATE ANY EDITION TO MSACCESS;
  GRANT CREATE ANY INDEX TO MSACCESS;
  GRANT CREATE ANY INDEXTYPE TO MSACCESS;
  GRANT CREATE ANY JOB TO MSACCESS;
  GRANT CREATE ANY LIBRARY TO MSACCESS;
  GRANT CREATE ANY MATERIALIZED VIEW TO MSACCESS;
  GRANT CREATE ANY MEASURE FOLDER TO MSACCESS;
  GRANT CREATE ANY MINING MODEL TO MSACCESS;
  GRANT CREATE ANY OPERATOR TO MSACCESS;
  GRANT CREATE ANY OUTLINE TO MSACCESS;
  GRANT CREATE ANY PROCEDURE TO MSACCESS;
  GRANT CREATE ANY SEQUENCE TO MSACCESS;
  GRANT CREATE ANY SQL PROFILE TO MSACCESS;
  GRANT CREATE ANY SYNONYM TO MSACCESS;
  GRANT CREATE ANY TABLE TO MSACCESS;
  GRANT CREATE ANY TRIGGER TO MSACCESS;
  GRANT CREATE ANY TYPE TO MSACCESS;
  GRANT CREATE ANY VIEW TO MSACCESS;
  GRANT CREATE ASSEMBLY TO MSACCESS;
  GRANT CREATE CLUSTER TO MSACCESS;
  GRANT CREATE CUBE TO MSACCESS;
  GRANT CREATE CUBE BUILD PROCESS TO MSACCESS;
  GRANT CREATE CUBE DIMENSION TO MSACCESS;
  GRANT CREATE DATABASE LINK TO MSACCESS;
  GRANT CREATE DIMENSION TO MSACCESS;
  GRANT CREATE EXTERNAL JOB TO MSACCESS;
  GRANT CREATE INDEXTYPE TO MSACCESS;
  GRANT CREATE JOB TO MSACCESS;
  GRANT CREATE LIBRARY TO MSACCESS;
  GRANT CREATE MATERIALIZED VIEW TO MSACCESS;
  GRANT CREATE MEASURE FOLDER TO MSACCESS;
  GRANT CREATE MINING MODEL TO MSACCESS;
  GRANT CREATE OPERATOR TO MSACCESS;
  GRANT CREATE PROCEDURE TO MSACCESS;
  GRANT CREATE PROFILE TO MSACCESS;
  GRANT CREATE PUBLIC DATABASE LINK TO MSACCESS;
  GRANT CREATE PUBLIC SYNONYM TO MSACCESS;
  GRANT CREATE ROLE TO MSACCESS;
  GRANT CREATE ROLLBACK SEGMENT TO MSACCESS;
  GRANT CREATE SEQUENCE TO MSACCESS;
  GRANT CREATE SESSION TO MSACCESS;
  GRANT CREATE SYNONYM TO MSACCESS;
  GRANT CREATE TABLE TO MSACCESS;
  GRANT CREATE TABLESPACE TO MSACCESS;
  GRANT CREATE TRIGGER TO MSACCESS;
  GRANT CREATE TYPE TO MSACCESS;
  GRANT CREATE USER TO MSACCESS;
  GRANT CREATE VIEW TO MSACCESS;
  GRANT DEBUG ANY PROCEDURE TO MSACCESS;
  GRANT DEBUG CONNECT SESSION TO MSACCESS;
  GRANT DELETE ANY CUBE DIMENSION TO MSACCESS;
  GRANT DELETE ANY MEASURE FOLDER TO MSACCESS;
  GRANT DELETE ANY TABLE TO MSACCESS;
  GRANT DROP ANY ASSEMBLY TO MSACCESS;
  GRANT DROP ANY CLUSTER TO MSACCESS;
  GRANT DROP ANY CONTEXT TO MSACCESS;
  GRANT DROP ANY CUBE TO MSACCESS;
  GRANT DROP ANY CUBE BUILD PROCESS TO MSACCESS;
  GRANT DROP ANY CUBE DIMENSION TO MSACCESS;
  GRANT DROP ANY DIMENSION TO MSACCESS;
  GRANT DROP ANY DIRECTORY TO MSACCESS;
  GRANT DROP ANY EDITION TO MSACCESS;
  GRANT DROP ANY INDEX TO MSACCESS;
  GRANT DROP ANY INDEXTYPE TO MSACCESS;
  GRANT DROP ANY LIBRARY TO MSACCESS;
  GRANT DROP ANY MATERIALIZED VIEW TO MSACCESS;
  GRANT DROP ANY MEASURE FOLDER TO MSACCESS;
  GRANT DROP ANY MINING MODEL TO MSACCESS;
  GRANT DROP ANY OPERATOR TO MSACCESS;
  GRANT DROP ANY OUTLINE TO MSACCESS;
  GRANT DROP ANY PROCEDURE TO MSACCESS;
  GRANT DROP ANY ROLE TO MSACCESS;
  GRANT DROP ANY SEQUENCE TO MSACCESS;
  GRANT DROP ANY SQL PROFILE TO MSACCESS;
  GRANT DROP ANY SYNONYM TO MSACCESS;
  GRANT DROP ANY TABLE TO MSACCESS;
  GRANT DROP ANY TRIGGER TO MSACCESS;
  GRANT DROP ANY TYPE TO MSACCESS;
  GRANT DROP ANY VIEW TO MSACCESS;
  GRANT DROP PROFILE TO MSACCESS;
  GRANT DROP PUBLIC DATABASE LINK TO MSACCESS;
  GRANT DROP PUBLIC SYNONYM TO MSACCESS;
  GRANT DROP ROLLBACK SEGMENT TO MSACCESS;
  GRANT DROP TABLESPACE TO MSACCESS;
  GRANT DROP USER TO MSACCESS;
  GRANT EXECUTE ANY ASSEMBLY TO MSACCESS;
  GRANT EXECUTE ANY CLASS TO MSACCESS;
  GRANT EXECUTE ANY INDEXTYPE TO MSACCESS;
  GRANT EXECUTE ANY LIBRARY TO MSACCESS;
  GRANT EXECUTE ANY OPERATOR TO MSACCESS;
  GRANT EXECUTE ANY PROCEDURE TO MSACCESS;
  GRANT EXECUTE ANY PROGRAM TO MSACCESS;
  GRANT EXECUTE ANY TYPE TO MSACCESS;
  GRANT EXECUTE ASSEMBLY TO MSACCESS;
  GRANT EXPORT FULL DATABASE TO MSACCESS;
  GRANT FLASHBACK ANY TABLE TO MSACCESS;
  GRANT FLASHBACK ARCHIVE ADMINISTER TO MSACCESS;
  GRANT FORCE ANY TRANSACTION TO MSACCESS;
  GRANT FORCE TRANSACTION TO MSACCESS;
  GRANT GLOBAL QUERY REWRITE TO MSACCESS;
  GRANT GRANT ANY OBJECT PRIVILEGE TO MSACCESS;
  GRANT GRANT ANY PRIVILEGE TO MSACCESS;
  GRANT GRANT ANY ROLE TO MSACCESS;
  GRANT IMPORT FULL DATABASE TO MSACCESS;
  GRANT INSERT ANY CUBE DIMENSION TO MSACCESS;
  GRANT INSERT ANY MEASURE FOLDER TO MSACCESS;
  GRANT INSERT ANY TABLE TO MSACCESS;
  GRANT LOCK ANY TABLE TO MSACCESS;
  GRANT MANAGE SCHEDULER TO MSACCESS;
  GRANT MANAGE TABLESPACE TO MSACCESS;
  GRANT MERGE ANY VIEW TO MSACCESS;
  GRANT ON COMMIT REFRESH TO MSACCESS;
  GRANT QUERY REWRITE TO MSACCESS;
  GRANT RESTRICTED SESSION TO MSACCESS;
  GRANT RESUMABLE TO MSACCESS;
  GRANT SELECT ANY CUBE TO MSACCESS;
  GRANT SELECT ANY CUBE DIMENSION TO MSACCESS;
  GRANT SELECT ANY MINING MODEL TO MSACCESS;
  GRANT SELECT ANY SEQUENCE TO MSACCESS;
  GRANT SELECT ANY TABLE TO MSACCESS;
  GRANT SELECT ANY TRANSACTION TO MSACCESS;
  GRANT UNDER ANY TABLE TO MSACCESS;
  GRANT UNDER ANY TYPE TO MSACCESS;
  GRANT UNDER ANY VIEW TO MSACCESS;
  GRANT UNLIMITED TABLESPACE TO MSACCESS;
  GRANT UPDATE ANY CUBE TO MSACCESS;
  GRANT UPDATE ANY CUBE BUILD PROCESS TO MSACCESS;
  GRANT UPDATE ANY CUBE DIMENSION TO MSACCESS;
  GRANT UPDATE ANY TABLE TO MSACCESS;
  -- 2 Tablespace Quotas for MSACCESS 
  ALTER USER MSACCESS QUOTA UNLIMITED ON IBATBS;
 