----DROP TABLESPACE IBAIDX INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE IBAIDX DATAFILE 
  '/webapp/IBAPP/ibaidx01.dbf' SIZE 2G AUTOEXTEND OFF,
  '/webapp/IBAPP/ibaidx02.dbf' SIZE 2G AUTOEXTEND OFF,
  '/webapp/IBAPP/ibaidx03.dbf' SIZE 3265M AUTOEXTEND ON NEXT 1M MAXSIZE 24G,
  '/webapp/IBAPP/ibaidx04.dbf' SIZE 3385M AUTOEXTEND ON NEXT 1M MAXSIZE 24G
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


---DROP TABLESPACE IBATBS INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE IBATBS DATAFILE 
  '/webapp/IBAPP/ibatbs01.dbf' SIZE 2G AUTOEXTEND OFF,
  '/webapp/IBAPP/ibatbs02.dbf' SIZE 2G AUTOEXTEND OFF,
  '/webapp/IBAPP/ibatbs03.dbf' SIZE 3G AUTOEXTEND ON NEXT 1G MAXSIZE 24G,
  '/webapp/IBAPP/ibatbs04.dbf' SIZE 3G AUTOEXTEND ON NEXT 1G MAXSIZE 24G,
  '/webapp/IBAPP/ibatbs05.dbf' SIZE 3G AUTOEXTEND ON NEXT 1G MAXSIZE 24G,
  '/webapp/IBAPP/ibatbs06.dbf' SIZE 3G AUTOEXTEND ON NEXT 1G MAXSIZE 24G
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


---DROP TABLESPACE IBATMP INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE IBATMP TEMPFILE 
  '/webapp/IBAPP/IBATMP02.dbf' SIZE 2G AUTOEXTEND ON NEXT 1G MAXSIZE 2G,
  '/webapp/IBAPP/IBATMP01.dbf' SIZE 2G AUTOEXTEND ON NEXT 1G MAXSIZE 2G
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;