version: "3.7"
services:
  
  scheduler_demo1:
    hostname: web-scheduler_demo1
    image: "10.90.2.111:5000/mtis/web-scheduler:latest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - ./config/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
      - /nfsshares/infr/scheduler/config/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
    ports:
      ['2443:8443','2991:9990']
    networks:
      mtis-swarm-network:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.role == manager'
      update_config:
        delay: 2s
        
  scheduler_demo2:
    hostname: web-scheduler_demo2
    image: "10.90.2.111:5000/mtis/web-scheduler:latest"
    volumes:
      - /etc/localtime:/etc/localtime:ro
     # - ./config/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
      - /nfsshares/infr/scheduler/config/standalone_demo2.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml:ro
    ports:
      ['7443:8443','7991:9990']
    networks:
      mtis-swarm-network:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.role == manager'
      update_config:
        delay: 2s      
networks:
  mtis-swarm-network:
    external: true
