version: '3.7'

services:
  agent:
    image: 10.90.2.111:5000/mtis/portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  server:
    image: 10.90.2.111:5000/mtis/portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nfsshares/portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true
