FROM jboss/wildfly:10.1.0.Final

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent \
&& mkdir -p /opt/jboss/wildfly/modules/system/layers/base/com/oracle/main/

COPY resources/ojdbc7.jar /opt/jboss/wildfly/modules/system/layers/base/com/oracle/main/
COPY configs/test/module.xml /opt/jboss/wildfly/modules/system/layers/base/com/oracle/main/
COPY configs/test/standalone.xml /opt/jboss/wildfly/standalone/configuration/
COPY resources/mtis-ear.ear /opt/jboss/wildfly/standalone/deployments/

EXPOSE 8080
EXPOSE 9990

#RUN /opt/jboss/wildfly/bin/standalone.sh

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]